### PR TITLE
Adapt plugin to 1.0 (breaking change)

### PR DESCRIPTION
**Pull request by ricardo-devis-agullo**
Elysia 1.0 has been released and there's a [breaking change with hooks](https://elysiajs.com/blog/elysia-10.html#hook-type-breaking-change), changing the default scope of .on handlers from global to local. This puts it explicitly to global so the plugin can work on 1.0. 

This is a breaking change so I updated to a major version.

### CODE REVIEW

**Comment by tnfAngel** [comment]
Would it be possible to make it configurable?

**Comment by ricardo-devis-agullo** [comment]
The only other configuration that would make sense is scoped, but I guess you could add a parameter to choose in options

**Comment by tnfAngel** [comment]
Thank you!

**Review by rayriffy — APPROVED** [review]
I might need to make changeset to be more descriptive but bumping to a new major is the right step. I will publish this major along with an attempt to revamp a documentation either tonight or tomorrow.

**Pull request merged**
